# Generated by Django 4.2.6 on 2023-11-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('classroom_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_title', models.TimeField(default=0.0)),
                ('classroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classSchedule.persondata')),
            ],
        ),
    ]
